"""initial

Revision ID: 8eae8e13c6a0
Revises: 
Create Date: 2026-05-29 18:26:03.667606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8eae8e13c6a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hl_address', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hl_address')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('hl_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trader_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('coin', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trader_id', sa.BigInteger(), nullable=False),
    sa.Column('max_allocation_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('copy_ratio_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_leverage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trader_stats',
    sa.Column('trader_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('pnl_usd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('roi_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('trader_id', 'period')
    )
    op.create_table('user_agents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_address', sa.Text(), nullable=False),
    sa.Column('agent_key_enc', sa.LargeBinary(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('hl_order_id', sa.BigInteger(), nullable=True),
    sa.Column('coin', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trades')
    op.drop_table('user_agents')
    op.drop_table('trader_stats')
    op.drop_table('subscriptions')
    op.drop_table('signals')
    op.drop_table('users')
    op.drop_table('traders')
    # ### end Alembic commands ###
